/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ManifiestoRouteImport } from './routes/manifiesto'
import { Route as DestinoRouteImport } from './routes/destino'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifiestoRoute = ManifiestoRouteImport.update({
  id: '/manifiesto',
  path: '/manifiesto',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinoRoute = DestinoRouteImport.update({
  id: '/destino',
  path: '/destino',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/destino': typeof DestinoRoute
  '/manifiesto': typeof ManifiestoRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/destino': typeof DestinoRoute
  '/manifiesto': typeof ManifiestoRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/destino': typeof DestinoRoute
  '/manifiesto': typeof ManifiestoRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/destino' | '/manifiesto' | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/destino' | '/manifiesto' | '/sponsors'
  id: '__root__' | '/' | '/contacto' | '/destino' | '/manifiesto' | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  DestinoRoute: typeof DestinoRoute
  ManifiestoRoute: typeof ManifiestoRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifiesto': {
      id: '/manifiesto'
      path: '/manifiesto'
      fullPath: '/manifiesto'
      preLoaderRoute: typeof ManifiestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destino': {
      id: '/destino'
      path: '/destino'
      fullPath: '/destino'
      preLoaderRoute: typeof DestinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  DestinoRoute: DestinoRoute,
  ManifiestoRoute: ManifiestoRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
